# Site wide configuration

title: "Jeanie Lam"
description: "Just a Computer Science student blogging about her weekly meal preps"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: 
feed:
  path: atom.xml
paginate: 1
paginate_path: "/blog/:num/"
# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts

# Site owner
owner:
  name: Jeanie Lam
  email:
  twitter: jeanielam
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: headshot.png # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
